name: scan-and-patch-image
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.actor }}/vuln-nginx:latest

jobs:
  patch:
    runs-on: ubuntu-latest
    environment: GITHUB_TOKEN
    steps:
      - name: Log in to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Scan current image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: json
          output: trivy-report.json
          vuln-type: os
          ignore-unfixed: true      # only report vulns that have a fix
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Any fixable vulns?
        id: check
        run: |
          n=$(jq '[.Results[]?.Vulnerabilities[]?] | length' trivy-report.json)
          echo "count=$n" >> "$GITHUB_OUTPUT"

      # Use custom docker socket for buildkit
      - name: Set up Docker
        uses: docker/setup-docker-action@v5
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Get socket path
        run: |
            url=$(docker context inspect | jq -r .[0].Endpoints.docker.Host)
            socket_path=$(echo "$url" | awk -F// '{print $2}')
            echo "$socket_path"
            echo "SOCKET=$socket_path" >> $GITHUB_ENV

      - name: Patch with Copa
        if: steps.check.outputs.count != '0'
        id: copa
        uses: project-copacetic/copa-action@v1.2.1
        with:
          image: ${{ env.IMAGE }}
          image-report: trivy-report.json
          patched-tag: patched
          custom-socket: ${{ env.SOCKET }}

      - name: Re-scan patched image (gate)
        if: steps.check.outputs.count != '0'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ steps.copa.outputs.patched-image }}
          vuln-type: os
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: '1'

      - name: Log in and push patched image
        if: steps.check.outputs.count != '0'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ${{ steps.copa.outputs.patched-image }}
